dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'

# change the build directory to be within react's scope
#project_structure:
#    build: client/src/artifacts

      
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env


networks:
  default: development
  development:
    cmd_settings:
      mnemonic: brownie
      default_balance: 100000000000000000000
      unlock: 0xE94a9A06389CEf9370a9b64E478040Efb46856F9 # optionally add saved brownie account to Ganache
      # (requires explicit transfer of eth to accounts[-1]) 

    update_interval: 60
    verify: False
  
  kovan:
    verify: False
    update_interval: 60
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    fau_token: '0xFab46E002BbF0b4509813474841E0716E6730136'
    dai_usd_price_feed: '0x777A68032a88E5A84678A77Af2CD65A7b3c0775a'
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'

wallets:
  from_key: ${PRIVATE_KEY}


# enable output of development artifacts to load with react
dev_deployment_artifacts: true
